### ISSUE TITLE
StatusChangeListener

### ISSUE THREAD

**Issue by rafal-software** [VOL3/v-ol3#30]
Is it possible to use:
org.vaadin.gwtol3.client.view.StatusChangeListener ?

**Comment by mhosio** [comment]
Thank you for opening the issue. This is not doable with the current version. I'll add support for those in the next version.

**Comment by rafal-software** [comment]
When are you going to publish next version?
I`m asking becasuse your addon is very good job and I think that implementation of StatusChangeListener is very important and it takes not a lot of time...

**Comment by mhosio** [comment]
Unfortunately I am quite busy with other duties at the moment. However, I just pushed a fix that adds support for these. Please checkout and give it a try. Can not promise release date for the next official version though.

**Comment by rafal-software** [comment]
Unfortunately it seems to not working :-(
      OLView view = new OLView();
        view.setZoom(1);
        view.setCenter(0, 0);
        view.addViewChangeListener(new ViewChangeListener(){

            public void resolutionChanged(Double newResolution) {
               System.out.println("Resolution changed!");
            }

            public void rotationChanged(Double rotation) {
                
            }

            public void centerChanged(OLCoordinate centerPoint) {
                System.out.println("Center changed!");
            }

            public void zoomChanged(Integer zoom) {
               System.out.println("Zoom changed!");
            }


        
        });

**Comment by mhosio** [comment]
OK. It seems I did not test the right way. New patch applied and this time it also flushes the changes to the server immediately instead of waiting for some other user action. Thanks for the heads up.
