### ISSUE TITLE
Changing the OLZoomToExtentControl.extent after the map is sent to the client has no effect

### ISSUE THREAD

**Issue by viliam-durina** [VOL3/v-ol3#34]
I change markers on the map dynamically and I want to change the extent for the ZoomToExtentControl while the map is displayed. Am I missing something or is this not supported? If not, could you give me a hint about how to implement it, I could try. I think the OLZoomToExtentControl shoud be a com.vaadin.ui.Component...

**Comment by mhosio** [comment]
Did you try to create a new instance of the ZoomToExtent control and use
map.setZoomToExtentControl with the new instance? At the moment you cannot
change control attributes after the map has been rendered.

-Matti

**Comment by viliam-durina** [comment]
This works, thanks.
