### ISSUE TITLE
Support for context menu 

### ISSUE THREAD

**Issue by edwin-cox** [VOL3/v-ol3#42]
Vaadin has a way to handle context menus with action handlers that was supported in v-ol for the whole map component. However this feature seems to not work in v-ol3, since the popup menu doesn't appear. No exception was noticed.

**Comment by mhosio** [comment]
Planning to implement some type of a support for this. In the mean time, you could use the ContextMenu add-on from the directory to show your context menu.

**Comment by mhosio** [comment]
Now the api has a static context menu implementation and abstract base class for more dynamic ones. Marking this as resolved.
