### ISSUE TITLE
Setting specific order of layers

### ISSUE THREAD

**Issue by Styp** [VOL3/v-ol3#45]
![gis_layers](https://cloud.githubusercontent.com/assets/1202069/9061903/1c6fff16-3abf-11e5-9b16-1d83db7a4e8b.gif)

Occording to this graphic it would be nice to set a fixed position on each layer. In the end this could be very usefull give a little more order to things...

**Comment by Infiniverse** [comment]
Does OpenLayers support ordering natively?

**Comment by Styp** [comment]
According to my research, it should work:
http://openlayers.org/en/v3.14.2/apidoc/ol.Collection.html

The canvas renders the layers according to the position in the list. If you change the position the canvas is different...

Do you have another idea?

**Comment by Ayora29** [comment]
Hello,

According to this doc :
http://openlayers.org/en/v3.9.0/examples/layer-z-index.html

Openlayer support z-index ordering since version 3.9.0.
It would be great to have support for z-index ordering in the GWT Wrapper.

**Comment by mhosio** [comment]
Hi,

Just committed a patch for this. It was part of a bigger changeset originally, but extracted it quickly. Could either one of you try it out and see if it works.

**Comment by Ayora29** [comment]
Ok thanks I will test it :)
