### ISSUE TITLE
Add support for Bing maps

### ISSUE THREAD

**Issue by mhosio** [VOL3/v-ol3#49]

**Comment by Infiniverse** [comment]
Hey there, is there any update on when this might be coming? :)

**Comment by mhosio** [comment]
Hello!

Unfortunately can not promise anything. But it is on my backlog and I will implement that as soon as I can squeeze in some time to work with the add-on again.

**Comment by Styp** [comment]
@mhosio: Please do a code review on this! It works and is clean, but needs a second opinion...

@kiru: Thanks for the help ;)

**Comment by Infiniverse** [comment]
Thanks @Styp! I'll take a look as soon as I can.

**Comment by mhosio** [comment]
Hi!

Did a quick code review. Looks quite clean to me. Few improvements suggestions:
1) OLBingSourceOptions setters should return this
2) OLBingSourceOptions setter for map type should use string parameter. We still could have static string constants for available options as separate class (like now) or as an embedded class in the source which would reduce class clutter in the source package. I am afraid that using enum will require us to make immediate changes when new options become available in the bing maps.
3) Check map type name strings. https://msdn.microsoft.com/en-us/library/gg427625.aspx (ignore first typo :))
4) Client-side source options java docs should be fixed (copy-paste)

After fixing those, this looks really good to me.
