### ISSUE TITLE
Features being added to a modification interaction, where a restriction was originally applied.

### ISSUE THREAD

**Issue by Infiniverse** [VOL3/v-ol3#57]
I've found a bug with the modification interaction.

The ```OLModifyInteractionConnector``` adds features to the interaction whenever they are added to the layer. This is wrong though, in the case where the interaction was created for a restricted set of features. Otherwise, new features added to the layer become editable, which shouldn't happen if the edit was restricted.

After  the following interactions on a vector source:
```
vectorSource.addFeature(feature1)
vectorSource.addFeature(feature2)
map.addInteraction(new OLModifyInteraction(layer, new OLModifyInteractionOptions(), feature2))
vectorSource.addFeature(feature3)
```

I find that feature1 is not editable, and feature2 is editable. However, feature3 is _also_ editable.

The fix is:

```
    diff --git a/v-ol3/src/main/java/org/vaadin/addon/vol3/client/interaction/OLModifyInteractionConnector.java b/v-ol3/src/main/java/org/vaadin/addon/vol3/client/interaction/OLModifyInteractionConnector.java
    index 6cd1df4..357861a 100644
    --- a/v-ol3/src/main/java/org/vaadin/addon/vol3/client/interaction/OLModifyInteractionConnector.java
    +++ b/v-ol3/src/main/java/org/vaadin/addon/vol3/client/interaction/OLModifyInteractionConnector.java
    @@ -93,7 +97,5 @@ public class OLModifyInteractionConnector extends OLInteractionConnector impleme
         }
    
         @Override
    -    public void featureAdded(Feature feature) {
    -        targetFeatures.push(feature);
    -    }
    +    public void featureAdded(Feature feature) { }
     }
```

**Comment by Styp** [comment]
Can you provide me some demo code?

Unfortunately, I can not reproduce the bug...

**Comment by Infiniverse** [comment]
I couldn't either, when I tried; but then I worked it out. The additional feature needs to be added later - which I'm emulating here by added it on a mouse click on the map.

See the attached code. In this example three squares are displayed; one and two are marked as editable and three isn't. (which you can verify by hovering the mouse over the features).

When you click in the map a fourth feature is added. Notice, by hovering the mouse over it, that this feature is now editable.

This is because the feature was added to targetFeatures within OLModifyInteractionConnector.

That looks like a bug to me; it was probably added to deal with the case of having new features editable in the case where no features are specified in the modification interaction. However, that case is already dealt with by the code.

[OL3Demo.java.txt](https://github.com/VOL3/v-ol3/files/56728/OL3Demo.java.txt)

**Comment by Infiniverse** [comment]
Hi Styp, any news on this? Can we get the putt request applied please? Many thanks, Joe

**Comment by Styp** [comment]
Sorry took me a while to reproduce everything. I think your fix works.
Thank you!
