### ISSUE TITLE
Feature Request: Support select condition on OLSelectInteraction.

### ISSUE THREAD

**Issue by Infiniverse** [VOL3/v-ol3#59]
OpenLayers supports different kinds of select interactions, allowing for single click/double click, etc.

http://openlayers.org/en/v3.8.2/examples/select-features.html

We have a need for a 'click' - which reports faster than the default 'single click'.

I've added this issue as a placeholder that this feature is requested.

**Comment by Styp** [comment]
I don't see why this should be faster...
Not sure, maybe you can explain me your idea - implementation should be doable...

**Comment by Infiniverse** [comment]
We don't need this anymore.
