### ISSUE TITLE
MapQuest appkey option

### ISSUE THREAD

**Issue by KchoXy** [VOL3/v-ol3#78]
Hi,

Since the last changes in the API, you can not access the application without a key. Could add an option to continue using the MapQuest map?

See this for more information: http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by mhosio** [comment]
Since this is only a wrapper around the awesome OpenLayers 3 js-lib, the OpenLayers guys needs to get this fixed first.

See https://github.com/openlayers/ol3/issues/5484
