### ISSUE TITLE
Vaadin 8

### ISSUE THREAD

**Issue by gokgozf** [VOL3/v-ol3#94]
In the readme.md states that the widget is for vaadin 7
Will Vaadin 8 be supported?

**Comment by gokgozf** [comment]
If you plan to create another major version, i might send a pull request for it.
Just wondering wheter it is expected to have Vaadin 8 support in the releases
or not, any idea?

Best

**Comment by initialflame** [comment]
We are interested in a Vaadin 8 compatible Version too...

**Comment by arioko** [comment]
Please, we need Vaadin 8 compatible version. Thanks!
